### ISSUE TITLE
No unboxing of Buffer under IO

### ISSUE THREAD

**Issue by AndrasKovacs** [fumieval/mason#1]
As far as I know, GHC (up to 8.6.1 at least) does not unpack tuples under `IO`. Hence, `s -> Buffer -> IO Buffer` in `BuilderFor` always returns with an extra heap indirection. This can be fixed by using `RealWorld#` and unboxing manually. I'm not sure if this makes a significant difference here, I'm just noting it as a potential optimization.

**Comment by fumieval** [comment]
`Buffer` is infrequently allocated because worker-wrapper transformation merges a chain of `Builder` actions. `fast-builder` does such optimisation, but it doesn't seem to make a big difference given that mason is equally fast in many cases.

**Comment by fumieval** [comment]
The definition of BuilderFor has been reworked using unboxed tuples. I confirmed that this helps when a chain of builders is not fully inlined.
