### ISSUE TITLE
Impredictive polymorphism issue

### ISSUE THREAD

**Issue by yaitskov** [fumieval/mason#2]
Hi,

I tried to replace ByteString.Builder with Mason.
According to the docs it looks pretty easy - just replace imports and add new cabal dependency,
but GHC fails with on every function mentionting Builder with following error?

```
    • Illegal polymorphic type: forall s. Buildable s => BuilderFor s
      GHC doesn't yet support impredicative polymorphism
    • In the expansion of type synonym ‘Builder’
      In the type signature: mm :: IO (IORef (Int, Builder))
   |
52 | mm :: IO (IORef (Int, MB.Builder))

```
If Builder type cannot be use in functions this fact should mentioned, cause
it limits library capability.

If not an example with tricky configuration would be helpful.

**Comment by fumieval** [comment]
You can use http://hackage.haskell.org/package/mason-0.2/docs/Mason-Builder-Dynamic.html instead; `DynBuilder` doesn't contain any polymorphism. I'll think about adding a module which can be used as a drop-in replacement.

**Comment by fumieval** [comment]
Can you try the newly-added `Mason.Builder.Compat` from 97fbb90f030e3baa7dd3c77e2ce6defcc4e2249a?

**Comment by yaitskov** [comment]
@fumieval , very thanks for platinum support ;)

I tried compat module. Here is my feed back below.
My use case is combining user eventlog messages in OpenTelemetry.
I need bufferization, because I noticed pure performance on writing short messages. 
1.6 ms vs 366 ns (with thread local and Builder)
https://github.com/ethercrow/opentelemetry-haskell/pull/19


 With ByteString.Builder (best/worst out of 3)
```
time                 350.5 ns   (349.4 ns .. 351.7 ns)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 350.7 ns   (349.4 ns .. 353.6 ns)
std dev              6.392 ns   (2.959 ns .. 12.86 ns)
variance introduced by outliers: 22% (moderately inflated)

time                 352.2 ns   (350.7 ns .. 353.8 ns)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 353.6 ns   (352.5 ns .. 354.5 ns)
std dev              3.370 ns   (2.710 ns .. 4.344 ns)
```

with Mason.Compat (best/worst out of 3)
```
time                 349.7 ns   (348.2 ns .. 351.7 ns)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 347.6 ns   (346.5 ns .. 349.2 ns)
std dev              4.275 ns   (3.268 ns .. 6.020 ns)
variance introduced by outliers: 11% (moderately inflated)

time                 351.7 ns   (351.0 ns .. 352.7 ns)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 352.9 ns   (351.3 ns .. 355.5 ns)
std dev              6.519 ns   (4.423 ns .. 9.449 ns)
variance introduced by outliers: 23% (moderately inflated)

```
