### ISSUE TITLE
Add benchmarks to haskell-perf/strict-bytestring-builders

### ISSUE THREAD

**Issue by chshersh** [fumieval/mason#3]
Hi! Thanks for implementing and maintaining this awesome library! I'm currently looking for the ByteString builder library, and I wonder, what is the fastest option available in Haskell.

There's the benchmark of all bytestring builders in the `haskell-perf` organization:

* https://github.com/haskell-perf/strict-bytestring-builders

But I see that it lacks the benchmark with `mason`. I think it would be lovely and beneficial for the community, if you could provide implementation of the existing bench suite for `mason`, so all existing libraries will be covered🙂 Also, according to the `strict-bytestring-builders` benchmark, the `bytestring-strict-builder` library is the fastest at the moment, but I'm curious, how it compares to `mason` 🤔

**Comment by fumieval** [comment]
Thanks for reminding! I actually had the change but forgot to submit it. Here's the PR: https://github.com/haskell-perf/strict-bytestring-builders/pull/5

You might also be interested in [bytes-builder-shootout](https://github.com/andrewthad/bytes-builder-shootout), and its [result](https://github.com/haskell/bytestring/issues/194#issuecomment-650706975).

**Comment by fumieval** [comment]
`bytestring-strict-builder` is indeed fast, but it can't produce lazy bytestring or write to the handle in an incremental manner.

**Comment by chshersh** [comment]
@fumieval Thanks for your reply and your work on bytestring builders! That answers my question. Feel free to close the issue 🙂
