### ISSUE TITLE
doubleDec is broken

### ISSUE THREAD

**Issue by nikita-volkov** [fumieval/mason#5]
```
> doubleDec 6.248372003193505e15 & toStrictByteString 
"6248372003193505"
```

**Comment by fumieval** [comment]
Is it really broken though?

```
Prelude> log 6.248372003193505e15
36.371097345239285
Prelude> log 6248372003193505
36.371097345239285
```

**Comment by nikita-volkov** [comment]
Hmm. Arguable, I agree.

Worth noting though, that Data.ByteString.Builder does it differently:
```
> import qualified Data.ByteString.Builder as BB
> BB.doubleDec 6.248372003193505e15 & BB.toLazyByteString  
"6.248372003193505e15"
```

**Comment by fumieval** [comment]
Right, bytestring's `doubleDec` calls `show` internally. We expect this kind of function to return the shortest representation, so we could as well say that `show` is broken.

**Comment by nikita-volkov** [comment]
Okay. I'm convinced :)
