### ISSUE TITLE
Intersperse's type signature is too specific

### ISSUE THREAD

**Issue by kozross** [fumieval/mason#6]
Currently, we have ``intersperse :: Buildable e => BuilderFor e -> [BuilderFor e] -> BuilderFor e``. However, this is too restrictive, as it should be able to be applied to any linear collection. Is there anything stopping us from having something like:

```haskell
intersperse :: (Buildable e, Foldable t) => BuilderFor e -> t (BuilderFor e) -> BuilderFor e
```

**Comment by fumieval** [comment]
Good point. It was just because other implementations from`base`, `bytestring` and `text` are restricted this way.
