### ISSUE TITLE
Support text 2.0

### ISSUE THREAD

**Issue by raehik** [fumieval/mason#8]
Version 2.0 for the `text` package switched to UTF-8 for internal representation, which included changing functions in `Data.Text.Array` from using `Word16` to `Word8`. Some CPP flagging should be able to fix this.

This should fix GHC 9.4 support, which seems to be failing because text-1.2.5.0 has some ghc-prim conflict with bytestring.

**Comment by raehik** [comment]
I intend to have a look at this a bit later!

**Comment by fumieval** [comment]
Thank you for the contribution!
